# -*- coding: utf-8 -*-
"""Ollama+Gemma4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pGQCbNYHDIZdH_QK0bdIh4tzf3SkX44Z

## Setting Up Ollama on Google Colab and Running Gemma4

### Installation
"""

!sudo apt-get install zstd
!curl -fsSL https://ollama.com/install.sh | sh

#WARNING: Unable to detect NVIDIA/AMD GPU. Install lspci or lshw to automatically detect and install GPU dependencies.
!sudo apt update && sudo apt install pciutils lshw

"""### GPU Enabled"""

!nvidia-smi

"""### Running Ollama Server

Running on a cell leads to getting stuck in that cell, so run it as background process.
"""

# !ollama serve

# 1. Kill any existing instances
# !pkill ollama

# 2. Set the environment variable to allow connections
import os
os.environ['OLLAMA_HOST'] = '0.0.0.0:11434'

# 3. Start the server in the background
import subprocess
import time
subprocess.Popen(["ollama", "serve"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

# 4. Wait for it to warm up
time.sleep(10)
print("Server should be ready.")

"""### Testing if Ollama is Running"""

!curl http://localhost:11434

"""### Install Ollama Python SDK

It makes using Ollama easy. We can access Ollama programmatically.
"""

!pip install ollama

"""### Download Gemma4:e2b Model: Run this on terminal

`ollama pull gemma4:e2b`

### Checking Model List In Ollama
"""

!ollama list

"""### Testing Gemma4 on Text Input"""

import ollama
response = ollama.chat(model='gemma4:e2b', messages=[
  {'role': 'user', 'content': 'Why is the sky blue?'},
])
print(response['message']['content'])

"""### Download an Image"""

!wget https://upload.wikimedia.org/wikipedia/commons/d/d9/Collage_of_Nine_Dogs.jpg

"""### Testing Gemma4 On Image Input"""

import base64

# --- How to prepare your image ---
with open("./Collage_of_Nine_Dogs.jpg", "rb") as image_file:
  encoded_image = base64.b64encode(image_file.read()).decode('utf-8')


# Make the call to the model with the image
response = ollama.chat(
    model='gemma4:e2b',
    messages=[
        {
            'role': 'user',
            'content': 'Describe this image.', # content should be a string
            'images': [encoded_image] # images is a list of base64 strings within the message
        }
    ]
)

print(response['message']['content'])

!nvidia-smi

