import os
import shutil
import pandas as pd
import matplotlib.pyplot as plt
from eplus.colab_bootstrap import prepare_colab_eplus

def run_simulation_job(job_id, idf_path, epw_path, config=None, output_dir_base="sim_runs"):
    """
    Executes an EnergyPlus simulation for a specific job.
    
    Args:
        job_id (str): Unique Job ID.
        idf_path (str): Path to the model.idf file.
        epw_path (str): Path to the weather.epw file.
        config (dict): Simulation configuration (e.g., {"run_type": "annual", "outputs": [...]}).
        output_dir_base (str): Base directory for simulation outputs.
        
    Returns:
        dict: Paths to result files (images, csvs, sql).
    """
    if config is None:
        config = {}
        
    # 1. Prepare Colab Environment (Safe to call repeatedly)
    print(f"[{job_id}] Bootstrapping EnergyPlus (Verbose)...")
    prepare_colab_eplus(silent=False)
    
    # Lazy import to avoid loading pyenergyplus before bootstrap
    from eplus.eplus_util import EPlusUtil
    from eplus.sql_explorer import EPlusSqlExplorer
    
    # 2. Setup Run Directory
    run_dir = os.path.join(output_dir_base, job_id)
    if os.path.exists(run_dir):
        shutil.rmtree(run_dir)
    os.makedirs(run_dir, exist_ok=True)
    
    # 3. Initialize Utility
    print(f"[{job_id}] Initializing EPlusUtil...")
    util = EPlusUtil(verbose=1)
    
    # 4. Configure Model
    # Note: We assume the IDF is already patched/generated by Layer 4 (AI)
    # If the config requests CO2 patching, we can do it here, but ideally AI handles the structure.
    util.set_model(idf=idf_path, epw=epw_path, out_dir=run_dir)
    
    # 5. Setup Outputs
    # Ensure we get SQL output for data mining
    util.ensure_output_sqlite()
    
    # If users asked for specific variables, add them
    user_vars = config.get("outputs", [])
    if user_vars:
        # Convert list of strings to dict format required by ensure_output_variables
        # Defaulting to hourly for visualization if not specified
        var_specs = [{"name": v, "key": "*", "freq": "Hourly"} for v in user_vars]
        util.ensure_output_variables(var_specs)
    else:
        # Default "Sensible" outputs if none requested
        util.ensure_output_variables([
            {"name": "Zone Air Temperature", "key": "*", "freq": "Hourly"},
            {"name": "System Node Mass Flow Rate", "key": "*", "freq": "Hourly"},
            {"name": "Site Outdoor Air Drybulb Temperature", "key": "Environment", "freq": "Hourly"}
        ])

    # 6. Run Simulation
    run_type = config.get("run_type", "design_day").lower() # Default to design_day for speed
    print(f"[{job_id}] Starting Simulation (Type: {run_type})...")
    
    try:
        if "annual" in run_type:
            util.run_annual()
        else:
            # Default to design day
            util.run_design_day()
    except Exception as e:
        print(f"[{job_id}] Simulation Failed: {e}")
        raise e

    print(f"[{job_id}] Simulation Complete. Extracting Results...")

    # 7. Extract Results (Data Mining)
    results = {}
    sql_path = os.path.join(run_dir, "eplusout.sql")
    if not os.path.exists(sql_path):
        err_path = os.path.join(run_dir, "eplusout.err")
        err_msg = ""
        if os.path.exists(err_path):
            with open(err_path, "r", encoding="utf-8", errors="ignore") as f:
                err_msg = f.read()
        raise Exception(f"Simulation did not produce eplusout.sql.\\nEnergyPlus Engine Error Log:\\n{err_msg}")
        
    xp = EPlusSqlExplorer(sql_path)
    
    # Extract Key Variables for Plotting
    plot_vars = {
        "plot": "Zone Air Temperature",
        "plot_ekf": "System Node Mass Flow Rate",
        "plot_weather": "Site Outdoor Air Drybulb Temperature",
        "plot_energy": "DistrictHeatingWater:Facility"
    }

    for key, var_name in plot_vars.items():
        try:
            df = xp.auto_extract_series(var_name, to_kwh=False, include_design_days=True)
            
            if df is not None and not df.empty:
                # Save Raw Data for primary plot
                if key == "plot":
                    csv_path = os.path.join(run_dir, "results.csv")
                    df.to_csv(csv_path, index=False)
                    results["csv"] = csv_path
                
                # Generate Plot
                img_path = os.path.join(run_dir, f"{key}.png")
                plt.figure(figsize=(10, 6))
                # plt.plot(df["timestamp"], df["value"], label=var_name)
                plt.plot(range(len(df)), df["value"], label=var_name)

                plt.title(f"{var_name} - Job {job_id}")
                plt.xlabel("Time")
                plt.ylabel("Value")
                plt.legend()
                plt.grid(True)
                plt.tight_layout()
                plt.savefig(img_path)
                plt.close() # Close figure to free memory
                
                results[key] = img_path
            else:
                print(f"[{job_id}] Warning: No data found for {var_name}")
        except Exception as e:
            print(f"[{job_id}] Error plotting {var_name}: {e}")
    
    # 8. Add SQL and IDF to results
    results["idf"] = idf_path
        
    return results
