import os
import shutil
import pandas as pd
import matplotlib.pyplot as plt
from eplus.colab_bootstrap import prepare_colab_eplus

def run_simulation_job(job_id, idf_path, epw_path, config=None, output_dir_base="sim_runs"):
    """
    Executes an EnergyPlus simulation for a specific job.
    
    Args:
        job_id (str): Unique Job ID.
        idf_path (str): Path to the model.idf file.
        epw_path (str): Path to the weather.epw file.
        config (dict): Simulation configuration (e.g., {"run_type": "annual", "outputs": [...]}).
        output_dir_base (str): Base directory for simulation outputs.
        
    Returns:
        dict: Paths to result files (images, csvs, sql).
    """
    if config is None:
        config = {}
        
    # 1. Prepare Colab Environment (Safe to call repeatedly)
    print(f"[{job_id}] Bootstrapping EnergyPlus (Verbose)...")
    prepare_colab_eplus(silent=False)
    
    # Lazy import to avoid loading pyenergyplus before bootstrap
    from eplus.eplus_util import EPlusUtil
    from eplus.sql_explorer import EPlusSqlExplorer
    
    # 2. Setup Run Directory
    run_dir = os.path.join(output_dir_base, job_id)
    if os.path.exists(run_dir):
        shutil.rmtree(run_dir)
    os.makedirs(run_dir, exist_ok=True)
    
    # 3. Initialize Utility
    print(f"[{job_id}] Initializing EPlusUtil...")
    util = EPlusUtil(verbose=1)
    
    # 4. Configure Model
    # Note: We assume the IDF is already patched/generated by Layer 4 (AI)
    # If the config requests CO2 patching, we can do it here, but ideally AI handles the structure.
    util.set_model(idf=idf_path, epw=epw_path, out_dir=run_dir)
    
    # 5. Setup Outputs
    # Ensure we get SQL output for data mining
    util.ensure_output_sqlite()
    
    # If users asked for specific variables, add them
    user_vars = config.get("outputs", [])
    if user_vars:
        # Convert list of strings to dict format required by ensure_output_variables
        # Defaulting to hourly for visualization if not specified
        var_specs = [{"name": v, "key": "*", "freq": "Hourly"} for v in user_vars]
        util.ensure_output_variables(var_specs)
    else:
        # Default "Sensible" outputs if none requested
        util.ensure_output_variables([
            {"name": "Zone Air Temperature", "key": "*", "freq": "Hourly"},
            {"name": "System Node Mass Flow Rate", "key": "*", "freq": "Hourly"},
            {"name": "Site Outdoor Air Drybulb Temperature", "key": "Environment", "freq": "Hourly"},
            {"name": "Zone Air System Sensible Cooling Energy", "key": "*", "freq": "Hourly"},
            {"name": "Zone Air System Sensible Heating Energy", "key": "*", "freq": "Hourly"}
        ])

    # 6. Run Simulation
    run_type = config.get("run_type", "design_day").lower() # Default to design_day for speed
    print(f"[{job_id}] Starting Simulation (Type: {run_type})...")
    
    try:
        if "annual" in run_type:
            util.run_annual()
        else:
            # Default to design day
            util.run_design_day()
    except Exception as e:
        print(f"[{job_id}] Simulation Failed: {e}")
        raise e

    print(f"[{job_id}] Simulation Complete. Extracting Results...")

    # 7. Extract Results (Data Mining)
    results = {}
    sql_path = os.path.join(run_dir, "eplusout.sql")
    if not os.path.exists(sql_path):
        err_path = os.path.join(run_dir, "eplusout.err")
        err_msg = ""
        if os.path.exists(err_path):
            with open(err_path, "r", encoding="utf-8", errors="ignore") as f:
                err_msg = f.read()
        raise Exception(f"Simulation did not produce eplusout.sql.\\nEnergyPlus Engine Error Log:\\n{err_msg}")
        
    xp = EPlusSqlExplorer(sql_path)
    
    # Extract Key Variables for Plotting
    plot_vars = {
        "plot": "Zone Air Temperature",
        "plot_ekf": "System Node Mass Flow Rate",
        "plot_weather": "Site Outdoor Air Drybulb Temperature",
        "plot_energy": "Electricity:Facility"
    }

    for key, var_name in plot_vars.items():
        try:
            df = xp.auto_extract_series(var_name, to_kwh=False, include_design_days=True)
            
            if df is not None and not df.empty:
                # Save Raw Data for primary plot
                if key == "plot":
                    csv_path = os.path.join(run_dir, "results.csv")
                    df.to_csv(csv_path, index=False)
                    results["csv"] = csv_path
                
                # Generate Plot
                img_path = os.path.join(run_dir, f"{key}.png")
                plt.figure(figsize=(10, 6))
                # plt.plot(df["timestamp"], df["value"], label=var_name)
                plt.plot(range(len(df)), df["value"], label=var_name)

                plt.title(f"{var_name} - Job {job_id}")
                plt.xlabel("Time")
                plt.ylabel("Value")
                plt.legend()
                plt.grid(True)
                plt.tight_layout()
                plt.savefig(img_path)
                plt.close() # Close figure to free memory
                
                results[key] = img_path
            else:
                print(f"[{job_id}] Warning: No data found for {var_name}")
        except Exception as e:
            print(f"[{job_id}] Error plotting {var_name}: {e}")
    
    # 8. Add SQL and IDF to results
    results["idf"] = idf_path
    
    # 9. Generate HTML Summary of IDF objects
    try:
        with open(idf_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()
        
        objects = []
        current_type = None
        current_name = None
        current_fields = []
        
        for raw_line in lines:
            line = raw_line.strip()
            if line.startswith('!') or not line:
                continue
                
            line_no_comment = line
            if '!' in line:
                line_no_comment = line[:line.index('!')].strip()
                
            if not current_type:
                if line_no_comment.endswith(','):
                    current_type = line_no_comment[:-1].strip()
                elif line_no_comment.endswith(';'):
                    objects.append({"type": line_no_comment[:-1].strip(), "name": "N/A", "fields": []})
                    current_type = None
            elif not current_name:
                if line_no_comment.endswith(',') or line_no_comment.endswith(';'):
                    current_name = line_no_comment[:-1].strip()
                    if line_no_comment.endswith(';'):
                        objects.append({"type": current_type, "name": current_name, "fields": []})
                        current_type = None
                        current_name = None
            else:
                # We are parsing fields
                current_fields.append(line)
                if line_no_comment.endswith(';'):
                    objects.append({"type": current_type, "name": current_name, "fields": list(current_fields)})
                    current_type = None
                    current_name = None
                    current_fields = []
                    
        grouped = {}
        for obj in objects:
            t = obj["type"]
            n = obj["name"]
            if t not in grouped:
                grouped[t] = []
            if n != "N/A" and n:
                grouped[t].append(obj)
                
        html = f'''<html><head><title>IDF Object Summary</title><style>
        body{{font-family: -apple-system, sans-serif; padding: 40px; background: #f8f9fa;}}
        .card{{background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-bottom: 20px; break-inside: avoid;}}
        h1{{color: #1a73e8;}} h2{{color: #333; font-size: 1.1em; border-bottom: 1px solid #eee; padding-bottom: 5px;}}
        ul{{list-style-type: none; padding-left: 0;}} li{{padding: 8px 0; border-bottom: 1px solid #f0f0f0;}}
        details{{margin-top: 5px;}} summary{{cursor: pointer; color: #1a73e8; font-weight: 500; outline: none; list-style: none; display: flex; align-items: center;}}
        summary::-webkit-details-marker {{display: none;}}
        summary::before {{content: "▶ "; font-size: 0.8em; margin-right: 5px; color: #888; transition: transform 0.2s;}}
        details[open] summary::before {{transform: rotate(90deg);}}
        .fields-list{{background: #fafafa; padding: 10px 15px; border-radius: 4px; margin-top: 5px; font-family: monospace; font-size: 0.9em; color: #555;}}
        .fields-list div{{padding: 2px 0;}}
        </style></head><body><h1>IDF Component Summary</h1><p style="color:gray">Job ID: {job_id}</p><div style="column-count: 2; column-gap: 40px;">'''
        
        for t in sorted(grouped.keys()):
            objs = grouped[t]
            if objs:
                html += f'<div class="card"><h2>{t} <span style="color:gray; font-weight:normal; font-size:0.8em;">({len(objs)})</span></h2><ul>'
                for obj in objs:
                    n = obj["name"]
                    fields = obj["fields"]
                    if not fields:
                        html += f'<li>{n}</li>'
                    else:
                        html += f'<li><details><summary>{n}</summary><div class="fields-list">'
                        for f in fields:
                            # Safely escape HTML characters like < and >
                            f_clean = f.replace("<", "&lt;").replace(">", "&gt;")
                            html += f'<div>{f_clean}</div>'
                        html += '</div></details></li>'
                html += '</ul></div>'
        html += '</div></body></html>'
        
        summary_path = os.path.join(run_dir, "summary.html")
        with open(summary_path, 'w', encoding='utf-8') as f:
            f.write(html)
            
        results["summary"] = summary_path
        print(f"[{job_id}] Successfully generated summary.html")
    except Exception as e:
        print(f"[{job_id}] Error generating summary: {e}")
        
    return results
